server:
  port: 8200
spring:
  application:
    name: chat
  cloud:
    stream:
      bindings:
        input:
          destination: reactive-social-application-chat
          group: reviews-chat
          content-type: application/json
        newComments:
          destination: reactive-social-application-user-chat
          group: reviews-user-chat
          content-type: application/json
        clientToBroker:
          destination: reactive-social-application-chat-user-messages
          group: app-chatMessages
        brokerToClient:
          destination: reactive-social-application-chat-user-messages
          group: topic-chatMessages