server:
  port: 8200
spring:
  application:
    name: chat
  cloud:
    stream:
      bindings:
        input:
          destination: reactive-social-application-chat
          group: comments-chat
          content-type: application/json
        newComments:
          destination: reactive-social-application-user-chat
          group: comments-user-chat
          content-type: application/json
        clientToBroker:
          destination: reactive-social-application-chat-user-messages
          group: app-chatMessages
        brokerToClient:
          destination: reactive-social-application-chat-user-messages
          group: topic-chatMessages
    gateway:
      routes:
        - id: imagesService
          uri: lb://IMAGES
          predicates:
            - Path=/imagesService/**
          filters:
            - RewritePath=/imagesService/(?<segment>.*),/$\{segment}
            - RewritePath=/imagesServicee, /
            - SaveSession
        - id: images
          uri: lb://IMAGES
          predicates:
            - Path=/images/**
          filters:
            - SaveSession
        - id: mainCss
          uri: lb://IMAGES
          predicates:
            - Path=/main.css
          filters:
            - SaveSession
        - id: commentsService
          uri: lb://IMAGES
          predicates:
            - Path=/comments/**
          filters:
            - SaveSession