server:
  port: 9090

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: reactive-social-application-products
          group: products-service
          content-type: application/json
        output:
          destination: reactive-social-application-shop
          group: products-chat
          content-type: application/json

  application:
    name: products